name: flutter_compass_demo
description: An example app demonstrating how to build a compass.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_compass: # ^0.7.0
    path: ../sdk
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true